'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/context/AuthContext';
import { CircularProgressbar, buildStyles } from 'react-circular-progressbar';
import 'react-circular-progressbar/dist/styles.css';

interface Question {
  question: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
}

interface Microtask {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  timeEstimate: number;
  status: 'pending' | 'in-progress' | 'completed';
  score?: number;
  timeSpent?: number;
  questions: Question[];
  resources: string[];
  milestone: string;
  completedAt?: string;
}

interface Goal {
  id: string;
  title: string;
  description: string;
  examType: string;
  timeframe: 'daily' | 'weekly';
  microtasks: Microtask[];
  progress: {
    totalTasks: number;
    completedTasks: number;
    completionRate: number;
    averageScore: number;
  };
}

export default function DailyTasksPage() {
  const { user, token } = useAuth();
  const [goals, setGoals] = useState<Goal[]>([]);
  const [selectedGoal, setSelectedGoal] = useState<Goal | null>(null);
  const [dailyTasks, setDailyTasks] = useState<Microtask[]>([]);
  const [activeTask, setActiveTask] = useState<Microtask | null>(null);
  const [timer, setTimer] = useState<number>(0);
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Timer effect
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (isTimerRunning && timer > 0) {
      interval = setInterval(() => {
        setTimer(timer => timer - 1);
      }, 1000);
    } else if (timer === 0 && isTimerRunning) {
      setIsTimerRunning(false);
      alert('Time\'s up for this task!');
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerRunning, timer]);

  // Fetch daily goals
  const fetchDailyGoals = async () => {
    if (!token) return;
    
    try {
      setLoading(true);
      const response = await fetch('http://localhost:8000/api/microtasks/goals?timeframe=daily', {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        const data = await response.json();
        setGoals(data.goals);
        
        // Auto-select first goal and set up today's tasks
        if (data.goals.length > 0) {
          const firstGoal = data.goals[0];
          setSelectedGoal(firstGoal);
          setDailyTasks(firstGoal.microtasks.filter((task: Microtask) => 
            task.status !== 'completed' || 
            (task.completedAt && new Date(task.completedAt).toDateString() === new Date().toDateString())
          ).slice(0, 5)); // Limit to 5 tasks per day
        }
      } else {
        throw new Error('Failed to fetch goals');
      }
    } catch (error) {
      console.error('Goals fetch error:', error);
      setError('Failed to load daily goals');
    } finally {
      setLoading(false);
    }
  };

  // Start a task with timer
  const startTask = async (task: Microtask) => {
    setActiveTask(task);
    setTimer(task.timeEstimate * 60); // Convert minutes to seconds
    setIsTimerRunning(true);

    if (!token) return;

    try {
      const response = await fetch(`http://localhost:8000/api/microtasks/microtasks/${task.id}/start`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      if (response.ok) {
        fetchDailyGoals();
      }
    } catch (error) {
      console.error('Start task error:', error);
    }
  };

  // Complete task with AI auto-generation
  const completeTask = async (taskId: string) => {
    if (!token || !activeTask) return;

    try {
      const response = await fetch(`http://localhost:8000/api/microtasks/microtasks/${taskId}/complete`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ 
          notes: 'Auto-completed by AI from daily tasks' 
        })
      });

      if (response.ok) {
        const data = await response.json();
        setActiveTask(null);
        setIsTimerRunning(false);
        setTimer(0);
        fetchDailyGoals();
        alert(`Task completed! AI generated: ${data.autoGenerated?.score}% score in ${data.autoGenerated?.timeSpent} minutes`);
      }
    } catch (error) {
      console.error('Complete task error:', error);
    }
  };

  // Pause/Resume timer
  const toggleTimer = () => {
    setIsTimerRunning(!isTimerRunning);
  };

  // Stop current task
  const stopTask = () => {
    setActiveTask(null);
    setIsTimerRunning(false);
    setTimer(0);
  };

  // Format time for display
  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'text-green-600 bg-green-100';
      case 'in-progress': return 'text-blue-600 bg-blue-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return 'text-green-600 bg-green-100';
      case 'medium': return 'text-yellow-600 bg-yellow-100';
      case 'hard': return 'text-red-600 bg-red-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  useEffect(() => {
    if (token) {
      fetchDailyGoals();
    }
  }, [token]);

  if (!user) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p className="text-lg">Please log in to access daily tasks.</p>
      </div>
    );
  }

  // Calculate today's progress
  const todayProgress = dailyTasks.length > 0 
    ? (dailyTasks.filter(task => task.status === 'completed').length / dailyTasks.length) * 100
    : 0;

  const completedToday = dailyTasks.filter(task => task.status === 'completed').length;
  const averageScore = dailyTasks
    .filter(task => task.score !== null && task.score !== undefined)
    .reduce((sum, task, _, arr) => sum + (task.score || 0) / arr.length, 0);

  return (
    <div className="space-y-6 p-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Daily Microtasks
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            {new Date().toLocaleDateString('en-US', { 
              weekday: 'long', 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>
        </div>
        
        {selectedGoal && (
          <div className="flex items-center gap-4">
            <select
              value={selectedGoal.id}
              onChange={(e) => {
                const goal = goals.find(g => g.id === e.target.value);
                if (goal) {
                  setSelectedGoal(goal);
                  setDailyTasks(goal.microtasks.filter(task => 
                    task.status !== 'completed' || 
                    (task.completedAt && new Date(task.completedAt).toDateString() === new Date().toDateString())
                  ).slice(0, 5));
                }
              }}
              className="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {goals.map(goal => (
                <option key={goal.id} value={goal.id}>
                  {goal.title}
                </option>
              ))}
            </select>
          </div>
        )}
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-md p-4">
          <p className="text-red-800">{error}</p>
        </div>
      )}

      {/* Today's Progress Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow text-center">
          <div className="w-20 h-20 mx-auto mb-4">
            <CircularProgressbar
              value={todayProgress}
              text={`${Math.round(todayProgress)}%`}
              styles={buildStyles({
                pathColor: '#0088FE',
                textColor: '#666',
                textSize: '24px',
              })}
            />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Today's Progress</h3>
        </div>
        
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow text-center">
          <p className="text-3xl font-bold text-green-600">{completedToday}</p>
          <p className="text-gray-600 dark:text-gray-400">Tasks Completed</p>
        </div>
        
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow text-center">
          <p className="text-3xl font-bold text-blue-600">{dailyTasks.length - completedToday}</p>
          <p className="text-gray-600 dark:text-gray-400">Tasks Remaining</p>
        </div>
        
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow text-center">
          <p className="text-3xl font-bold text-orange-600">
            {averageScore ? Math.round(averageScore) + '%' : 'N/A'}
          </p>
          <p className="text-gray-600 dark:text-gray-400">Average Score</p>
        </div>
      </div>

      {/* Active Task Timer */}
      {activeTask && (
        <div className="bg-gradient-to-r from-blue-500 to-purple-600 text-white p-6 rounded-lg shadow-lg">
          <div className="flex justify-between items-center">
            <div>
              <h3 className="text-xl font-semibold">Currently Working On:</h3>
              <p className="text-lg mt-1">{activeTask.title}</p>
              <p className="text-sm opacity-90 mt-1">{activeTask.description}</p>
            </div>
            <div className="text-right">
              <div className="text-4xl font-bold mb-2">{formatTime(timer)}</div>
              <div className="flex gap-2">
                <button
                  onClick={toggleTimer}
                  className="px-4 py-2 bg-white text-blue-600 rounded hover:bg-gray-100"
                >
                  {isTimerRunning ? 'Pause' : 'Resume'}
                </button>
                <button
                  onClick={stopTask}
                  className="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600"
                >
                  Stop
                </button>
              </div>
            </div>
          </div>
          
          {/* Quick Complete */}
          {activeTask.status === 'in-progress' && (
            <div className="mt-4 pt-4 border-t border-white/20">
              <p className="text-sm mb-2">Quick Complete (enter your score):</p>
              <div className="flex gap-2">
                <button
                  onClick={() => completeTask(activeTask.id)}
                  className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 font-medium"
                >
                  ✅ Complete Task (AI will evaluate)
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Daily Tasks */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
          Today's Microtasks
        </h2>
        
        {loading ? (
          <div className="text-center py-8">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto"></div>
            <p className="mt-4 text-gray-600">Loading daily tasks...</p>
          </div>
        ) : dailyTasks.length === 0 ? (
          <div className="text-center py-8">
            <p className="text-gray-600 dark:text-gray-400">No daily tasks available. Create a goal with daily timeframe to get started!</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {dailyTasks.map((task, index) => (
              <div 
                key={task.id} 
                className={`border rounded-lg p-4 ${
                  activeTask?.id === task.id 
                    ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20' 
                    : 'border-gray-200 dark:border-gray-700'
                }`}
              >
                <div className="flex justify-between items-start mb-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-lg font-medium text-gray-900 dark:text-white">
                        #{index + 1}
                      </span>
                      <h4 className="font-medium text-gray-900 dark:text-white">{task.title}</h4>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">{task.description}</p>
                    
                    <div className="flex gap-2 mb-2">
                      <span className={`px-2 py-1 rounded-full text-xs ${getStatusColor(task.status)}`}>
                        {task.status}
                      </span>
                      <span className={`px-2 py-1 rounded-full text-xs ${getDifficultyColor(task.difficulty)}`}>
                        {task.difficulty}
                      </span>
                      <span className="px-2 py-1 rounded-full text-xs bg-purple-100 text-purple-600">
                        {task.timeEstimate}min
                      </span>
                    </div>
                    
                    <div className="text-xs text-gray-500">
                      <p>Category: {task.category}</p>
                      {task.milestone && <p>Milestone: {task.milestone}</p>}
                    </div>
                  </div>
                </div>
                
                {/* Task Actions */}
                <div className="mt-3">
                  {task.status === 'pending' && (
                    <button
                      onClick={() => startTask(task)}
                      disabled={activeTask !== null}
                      className="w-full px-3 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {activeTask ? 'Another task is active' : 'Start Task'}
                    </button>
                  )}
                  
                  {task.status === 'in-progress' && activeTask?.id !== task.id && (
                    <button
                      onClick={() => startTask(task)}
                      className="w-full px-3 py-2 bg-yellow-500 text-white rounded hover:bg-yellow-600"
                    >
                      Resume Task
                    </button>
                  )}
                  
                  {task.status === 'completed' && (
                    <div className="text-center">
                      <div className="flex justify-between items-center text-sm">
                        <span className="text-green-600 font-medium">✓ Completed</span>
                        <span className="text-gray-600">Score: {task.score}%</span>
                      </div>
                      <p className="text-xs text-gray-500 mt-1">Time: {task.timeSpent}min</p>
                    </div>
                  )}
                </div>

                {/* Questions Preview */}
                {task.questions && task.questions.length > 0 && (
                  <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
                    <p className="text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Sample Questions ({task.questions.length}):
                    </p>
                    <p className="text-xs text-gray-600 dark:text-gray-400">
                      {task.questions[0].question?.substring(0, 80) || 'Sample question available'}...
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Study Tips */}
      <div className="bg-gradient-to-r from-green-500 to-blue-600 text-white p-6 rounded-lg shadow">
        <h3 className="text-lg font-semibold mb-3">💡 Daily Study Tips</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <p className="font-medium">Time Management:</p>
            <p>Use the Pomodoro technique - focus for the estimated time, then take a 5-minute break.</p>
          </div>
          <div>
            <p className="font-medium">Active Learning:</p>
            <p>Take notes, solve practice questions, and explain concepts in your own words.</p>
          </div>
          <div>
            <p className="font-medium">Progress Tracking:</p>
            <p>Aim for consistent daily progress rather than perfect scores every time.</p>
          </div>
          <div>
            <p className="font-medium">Stay Motivated:</p>
            <p>Celebrate small wins and track your improvement over time.</p>
          </div>
        </div>
      </div>
    </div>
  );
}